services:
  redis:
    image: redis:8
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./infrastructure/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-cli:
    image: redis:8
    container_name: redis_cli
    depends_on:
      - redis
    entrypoint: ["redis-cli", "-h", "redis"]
    stdin_open: true
    tty: true

  
volumes:
  redis_data: